name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.2.0'

      - name: Install project dependencies
        run: npm install

      - name: Run the unit tests
        run: npm run test

      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
